### ISSUE TITLE
[ENHANCEMENT] allow the use of the role to redhat like systems

### ISSUE THREAD

**Issue by bnoahpro** [Oefenweb/ansible-dnsmasq#14]
The role installs and configures dnsmasq in a debian-like system but it could be very useful if we could run this role for a redhat-like system.

Thanks.

**Comment by bnoahpro** [comment]
A little idea to able redhat like systems, the use of ansible module **package**.
In tasks/main.yml : 
```yaml
# tasks file
---
- name: install dependencies
  ansible.builtin.package:
    name: "{{ dnsmasq_dependencies }}"
    state: "{{ package_install_state | default('latest') }}"
  tags:
    - configuration
    - dnsmasq
```
